### ISSUE TITLE
Error with temp files

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#115]
Hi,
I tried to annotate a vcf file containing ~250 variant but it crashed while merging with bcftools. Even with 1 thread it split vcf in 13 pieces, meaning that I can't avoid merging step. 
Error: segmentation fault (core dumped)
Regarding what I have done, it seems that setting /tmp as the output for bcftools merge command raise this issue.
It would be nice to have the choice of this tmp folder in howard to avoid this problem.

Spec:

bcftools 1.18
Ubuntu 20.04.6 LTS
Latest version of howard from devel
Best,

JB

**Comment by antonylebechec** [comment]
Add an option for temporary directory (for duckDB): --tmp
Also an option for all duckDB settings: --duckdb_settings
