### ISSUE TITLE
Bad VCF output format

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#137]
Hi,
I ran howard to annotate a mono sample VCF with CADD annotations comming from DBNSFP 4.4a (one parquet folder for each databases),
After annotating, I saw that my resulting vcf is malformatted, and got extra columns instead of the tenth required in vcf file.
It appears that howard add column already present in the header of the input file in the columns field of the output vcf (example below)

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sample  CLASS   DB      DNA     END     GENE    MUT     PHEN    PROT     RANKSCORE       STRAND  SVLEN   SVTYPE
chr1    949363  CS2015176       G       A       .       .       CLASS=DM;MUT=ALT;GENE=ISG15;STRAND=+;DNA=NM_005101.4:c.4-1G>A;PHEN=Ulcerative_skin_lesions;RANKSCORE=0.11;CADD_raw=5.371775;CADD_raw_rankscore=0.94208;CADD_phred=34.0;CADD_raw_hg19=5.079502;CADD_raw_rankscore_hg19=0.93428;CADD_phred_hg19=33  GT:AD:DP        0/1:50,50:100   DM              NM_005101.4:c.4-1G>A            ISG15   ALT     Ulcerative_skin_lesions          0.11    +

cmd used:
howard annotation --input DM_HGMD.corrected.v2.test.vcf --output DM_HGMD.corrected.v2.test.cadd.vcf --assembly hg19 --annotations "dbNSFP4.4a.CADD.partition.parquet"

I sent you a part of the input and output vcf,

Best,

Jean-Baptiste

**Comment by JbaptisteLam** [comment]
Moreover if there is no annotations at all in INFO field, everything goes well

**Comment by antonylebechec** [comment]
This issue was due to explode infos needed before annotation. Columns were not removed after their used.
Done.
