### ISSUE TITLE
howard convert from vcf to tsv 

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#138]
Hi,

I converted a VCF to TSV with arg explode_infos, everything goes well but in my resulting TSV my #CHROM column is empty,
It's possibly due to an other column called chr in INFO field, (I saw that this column is empty too)
A good solution should be to rename the 8 main columns (from CHROM to INFO with underscore or whatever in duckdb)

Best,

Jean-Baptiste

**Comment by antonylebechec** [comment]
Due to INFO/field already existing (such as 'alt' in VCF format), it is not allowed to explode this field.
Use --explode_infos_prefix option to add a prefix on INFO_fields exploded, or --explode_infos_fields to choose INFO_fields you want to explode (and except 'alt' for example)
