### ISSUE TITLE
Trouble while using BED as annotation file

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#154]
Hi,

I wanted to annotate a vcf file with a BED containing annotations but it raised 2 issues:

- When using a compressed bed as input it raised a Samtools error
 raise SamtoolsError(
pysam.utils.SamtoolsError: 'bcftools returned with error -1: stdout=None, stderr=Writing to /tmp/howardo79lzk5l.vcf.gz.523.tmpJk1KDY\nError encountered while parsing the input at chr16:77319024\nCleaning\n'

- When using the same file but uncompressed it works, I am getting the good annotations but it add 'true' in ref column instead of reference base I had at the beginning

Best,

JB

**Comment by JbaptisteLam** [comment]
##fileformat=VCFv4.4
##fileDate=29/02/2024
##reference=hg19
##INFO=<ID=genes,Number=1,Type=String,Description="Gene symbol">
##INFO=<ID=OMIM_phenotype,Number=.,Type=String,Description="List of OMIM phenotype">
##INFO=<ID=OMIM_inheritance,Number=.,Type=String,Description="List of OMIM inheritance">
##INFO=<ID=OMIM_ID,Number=.,Type=Integer,Description="List of OMIM ID">
##INFO=<ID=transcript,Number=1,Type=String,Description="Refgene transcript">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Sample
chr1    8768495 .       true    C       .       .               GT      0/1

**Comment by JbaptisteLam** [comment]
chr16   8768473 8878427 NM_001386602    ABAT    GABA-transaminase deficiency| 613163 (3) AR     AR      137150

**Comment by antonylebechec** [comment]
That's strange.

If you look at this command:
```
howard annotation --input=tests/data/example.vcf.gz --output=/tmp/example.howard.vcf --annotations=tests/databases/annotations/current/hg19/annotation_regions.bed
```
You should have (something like 'annot1=blue,red;annot2=cherry,orange'):
```
grep "^#" -v /tmp/example.howard.vcf | cut -f1-8
chr1	28736	.	A	C	100	PASS	CLNSIG=pathogenic;annot1=blue,red;annot2=cherry,orange
chr1	35144	.	A	C	100	PASS	CLNSIG=non-pathogenic;annot1=blue,red;annot2=cherry,orange
chr1	69101	.	A	G	100	PASS	DP=50;annot1=blue,red;annot2=cherry,orange
chr1	768251	.	A	G	100	PASS	annot1=yellow;annot2=banana
chr1	768252	.	A	G	100	PASS	annot1=yellow;annot2=banana
chr1	768253	.	A	G	100	PASS	annot1=yellow;annot2=banana
chr7	55249063	rs1050171	G	A	5777	PASS	DP=125
```
