### ISSUE TITLE
Can't annotate with gnomad 3.0 parquet

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#155]
Hi,
I tried to annotate a vcf with gnomad 3.0 hg38 which is almost 15Go but it ran out of memory,
howard/howard/objects/variants.py", line 4549, in annotation_parquet
      result = self.conn.execute(query)
  duckdb.duckdb.OutOfMemoryException: Out of Memory Error: Failed to allocate block of 8192 bytes

I used a 64 cpu 1,5 To memory server, and already try to reduce chunksize or limit memory arg but still raising an error

Best,

JB

**Comment by JbaptisteLam** [comment]
The workaround is to reduce the number of threads even you have a lot available memory

**Comment by antonylebechec** [comment]
Thanks for the tip!
Does it worked with less threads?

**Comment by JbaptisteLam** [comment]
Reducing the number of threads works, closing this one :)

**Comment by JbaptisteLam** [comment]
Done
