### ISSUE TITLE
Howard from_annovar

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#156]
Hi,
args.input  and args.output return text.io wrapper object instead of str path,
A solution that worked for me is simply to add .name for both

Best,

JB

**Comment by antonylebechec** [comment]
Thanks!
I'll fix that asap. This is a tool that need to be fixed and updated. But that not a priority for now...

**Comment by antonylebechec** [comment]
fixed

**Comment by antonylebechec** [comment]
A fix of from_annovar is now able to take as input multiple format of TSV files. Indeed, this tool check header and try to identify chromosome, position, reference and alternative fields. This is not perfect, and adding a "fields_map" could be a solution to be more flexible (also a map for exclude and include columns). This tool has a low memory option that could be a solution for big files.
However, using [VariantConvert](https://github.com/SamuelNicaise/variantconvert) could be a better solution for complex file format
