### ISSUE TITLE
Error while exporting variant into vcf

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#231]
Hi,

In variants.py file func export_variant_vcf, 
It can not export a vcf which does not have FORMAT/SAMPLE field while these columns are not mandatory in vcf specifications.

Best,

JB

**Comment by antonylebechec** [comment]
Hi,

This fonction export by default samples. The parameter `add_samples` can exclude samples.
However, this function considers that samples are present in input VCF, which is not always the case.
So, this function will be fixed.

Thanks!
