### ISSUE TITLE
Potential Python Version Dependency Issue (Resolved)

### ISSUE THREAD

**Issue by judefelixt** [bioinfo-chru-strasbourg/howard#238]
I encountered challenges using Howard due to the Python version in my development environment. Here's a breakdown:

**Python 3.12.3**: The installation of Howard failed due to conflicts within its dependencies, particulary related to the pandas library.
**Python 3.10.0**: While Howard installed successfully with this version, I faced errors when processing .gz files.
**Python 3.10.13 (Success!)**: Using Python 3.10.13 resolved both installation and processing issues, allowing me to work with Howard seamlessly.

**Comment by bioinfo-chru-strasbourg** [comment]
Dear @judefelixt,

HOWARD was tested with Python 3.10.x versions, but not with 3.12.x. 

First of all, I was not able to reproduce the error when processing .gz file with version 3.10.0. Can you explain in detail your test?

For Python version 3.12.3, installation seems to fail:
```
Failed to build bgzip duckdb pyarrow pysam
```

Moreover, HOWARD was not tested with 3.11.x version.

So, I suggest to unsure version 3.10.x to install and use HOWARD. Use conda like this:
```
conda create -n howard python=3.10
conda activate howard
pip install -e .
howard --help
conda deactivate
```

**Comment by antonylebechec** [comment]
Some fixes and python release check
