### ISSUE TITLE
Error in prioritization step

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#272]
Maximum line size of 2097152 bytes exceeded. Actual Size:4507623 bytes.

Possible Solution: Change the maximum length size, e.g., max_line_size=4507624

  file=test.vcf
  delimiter =    (Set By User)
  quote = " (Auto-Detected)
  escape = \0 (Auto-Detected)
  new_line = Single-Line File (Auto-Detected)
  header = false (Auto-Detected)
  skip_rows = 143 (Set By User)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding=0
  sample_size=20480
  ignore_errors=false
  all_varchar=0

A workaround is to add "ignore_errors=True" in all query,

Best,

JB

**Comment by antonylebechec** [comment]
Can you provide the `test.vcf`file?
