### ISSUE TITLE
Download Annovar DB issue

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#35]
Thanks for your amazing annotation tools ;)

Got trouble to download annovar database with command below:
howard databases --assembly=hg38 --download-annovar=$PWD/annovar --download-annovar-files=refGene,gnomad_exome,dbnsfp42a,cosmic70,clinvar_202*,nci60 --threads=8 --verbosity=DEBUG

It correclty download refgene but after that it stop without downloading others db, I tried without '--download-annovar-files' option in order to download all available db from annovar but I get same issue, only refgene was downloaded,

Any workaround ?

Best 

JB

**Comment by antonylebechec** [comment]
Tried to reproduce the issue, but no error found:
 ```
$  howard databases --assembly=hg38 --download-annovar=/tmp/download_annovar_test/ --download-annovar-files=refGene,cosmic70,clinvar_202*,nci60 --threads=8 --verbosity=DEBUG
#[2023-04-28 23:16:41] [INFO] Start
#[2023-04-28 23:16:41] [INFO] Download Annovar databases ['hg38']
#[2023-04-28 23:16:41] [INFO] Download Annovar databases ['hg38']
#[2023-04-28 23:16:41] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20200316.txt.idx.gz' Downloading...
#[2023-04-28 23:16:42] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20210501.txt.idx.gz' Downloading...
#[2023-04-28 23:16:42] [INFO] Download Annovar databases ['hg38'] - file 'hg38_cosmic70.txt.gz' Downloading...
#[2023-04-28 23:16:45] [INFO] Download Annovar databases ['hg38'] - file 'hg38_nci60.txt.idx.gz' Downloading...
#[2023-04-28 23:16:46] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20220320.txt.gz' Downloading...
#[2023-04-28 23:16:50] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20221231.txt.idx.gz' Downloading...
#[2023-04-28 23:16:51] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneWithVerMrna.fa.gz' Downloading...
#[2023-04-28 23:17:01] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneMrna.fa.gz' Downloading...
#[2023-04-28 23:17:12] [INFO] Download Annovar databases ['hg38'] - file 'hg38_cosmic70.txt.idx.gz' Downloading...
#[2023-04-28 23:17:13] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20210501.txt.gz' Downloading...
#[2023-04-28 23:17:16] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneWithVer.txt.gz' Downloading...
#[2023-04-28 23:17:18] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20220320.txt.idx.gz' Downloading...
#[2023-04-28 23:17:19] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20210123.txt.gz' Downloading...
#[2023-04-28 23:17:22] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGene.txt.gz' Downloading...
#[2023-04-28 23:17:25] [INFO] Download Annovar databases ['hg38'] - file 'hg38_nci60.txt.gz' Downloading...
#[2023-04-28 23:17:26] [INFO] Download Annovar databases ['hg38'] - file 'hg38_clinvar_20210123.txt.idx.gz' Downloading...
#[2023-04-28 23:17:27] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneVersion.txt.gz' Downloading...
#[2023-04-28 23:17:27] [INFO] End
```

Can you specify your environment (e.g. OS)?
Can you provide log output? Please use --debug rather than --verbosity=DEBUG (see #36)

**Comment by JbaptisteLam** [comment]
Here is stdout of the command, working on linux Ubuntu 18, it seems that there is a trouble with download annovar files option set as none in args

#[2023-05-02 13:13:25] [DEBUG] Command/Tool: databases
#[2023-05-02 13:13:25] [INFO] Start
#[2023-05-02 13:13:25] [DEBUG] Args Namespace(command='databases', assembly=['hg38'], download_snpeff=None, download_annovar='./test-db', download_annovar_files=None, download_annovar_url='http://www.openbioinformatics.org/annovar/download/', config={'verbosity': 'debug', 'threads': '8'}, threads='8', verbosity='debug', quiet=False, verbose=False, debug=True)
#[2023-05-02 13:13:25] [DEBUG] Download Annovar databases
#[2023-05-02 13:13:25] [INFO] Download Annovar databases ['hg38']
#[2023-05-02 13:13:25] [DEBUG] Download Annovar for assembly 'hg38'
#[2023-05-02 13:13:25] [DEBUG] Download Annovar databases in folder './test-db'
#[2023-05-02 13:13:25] [DEBUG] Only mandatory files will be downloaded
#[2023-05-02 13:13:25] [DEBUG] Download list of Annovar files from Annovar URL
#[2023-05-02 13:13:25] [DEBUG] Download list of Annovar files hg38_avdblist.txt from Annovar URL http://www.openbioinformatics.org/annovar/download/hg38_avdblist.txt to Annovar folder ./test-db/hg38_avdblist.txt
#[2023-05-02 13:13:25] [DEBUG] Starting new HTTP connection (1): www.openbioinformatics.org:80
#[2023-05-02 13:13:26] [DEBUG] http://www.openbioinformatics.org:80 "GET /annovar/download/hg38_avdblist.txt HTTP/1.1" 200 5847
#[2023-05-02 13:13:26] [DEBUG] List of file in Annovar folder: ['hg38_refGeneWithVerMrna.fa.gz']
#[2023-05-02 13:13:26] [DEBUG] List of file in Annovar folder with size: {'hg38_refGeneWithVerMrna.fa.gz': 69772212}
#[2023-05-02 13:13:26] [DEBUG] List of file available in Annovar URL: ['hg38_refGene.txt.gz', 'hg38_refGeneWithVer.txt.gz', 'hg38_refGeneWithVerMrna.fa.gz', 'hg38_refGeneVersion.txt.gz', 'hg38_refGeneMrna.fa.gz']
#[2023-05-02 13:13:26] [DEBUG] List of file to download: ['hg38_refGene.txt.gz', 'hg38_refGeneWithVer.txt.gz', 'hg38_refGeneVersion.txt.gz', 'hg38_refGeneMrna.fa.gz']
#[2023-05-02 13:13:26] [INFO] Download Annovar databases ['hg38']
#[2023-05-02 13:13:26] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGene.txt.gz' Downloading...
#[2023-05-02 13:13:26] [DEBUG] Download file hg38_refGene.txt.gz from http://www.openbioinformatics.org/annovar/download/hg38_refGene.txt.gz to ./test-db/hg38_refGene.txt.gz...
#[2023-05-02 13:13:26] [DEBUG] Starting new HTTP connection (1): www.openbioinformatics.org:80
#[2023-05-02 13:13:26] [DEBUG] http://www.openbioinformatics.org:80 "GET /annovar/download/hg38_refGene.txt.gz HTTP/1.1" 200 8594720
#[2023-05-02 13:13:30] [DEBUG] Extract file hg38_refGene.txt.gz to ./test-db...
#[2023-05-02 13:13:31] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneWithVer.txt.gz' Downloading...
#[2023-05-02 13:13:31] [DEBUG] Download file hg38_refGeneWithVer.txt.gz from http://www.openbioinformatics.org/annovar/download/hg38_refGeneWithVer.txt.gz to ./test-db/hg38_refGeneWithVer.txt.gz...
#[2023-05-02 13:13:31] [DEBUG] Starting new HTTP connection (1): www.openbioinformatics.org:80
#[2023-05-02 13:13:31] [DEBUG] http://www.openbioinformatics.org:80 "GET /annovar/download/hg38_refGeneWithVer.txt.gz HTTP/1.1" 200 8653742
#[2023-05-02 13:13:34] [DEBUG] Extract file hg38_refGeneWithVer.txt.gz to ./test-db...
#[2023-05-02 13:13:35] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneVersion.txt.gz' Downloading...
#[2023-05-02 13:13:35] [DEBUG] Download file hg38_refGeneVersion.txt.gz from http://www.openbioinformatics.org/annovar/download/hg38_refGeneVersion.txt.gz to ./test-db/hg38_refGeneVersion.txt.gz...
#[2023-05-02 13:13:35] [DEBUG] Starting new HTTP connection (1): www.openbioinformatics.org:80
#[2023-05-02 13:13:35] [DEBUG] http://www.openbioinformatics.org:80 "GET /annovar/download/hg38_refGeneVersion.txt.gz HTTP/1.1" 200 199671
#[2023-05-02 13:13:35] [DEBUG] Extract file hg38_refGeneVersion.txt.gz to ./test-db...
#[2023-05-02 13:13:35] [INFO] Download Annovar databases ['hg38'] - file 'hg38_refGeneMrna.fa.gz' Downloading...
#[2023-05-02 13:13:35] [DEBUG] Download file hg38_refGeneMrna.fa.gz from http://www.openbioinformatics.org/annovar/download/hg38_refGeneMrna.fa.gz to ./test-db/hg38_refGeneMrna.fa.gz...
#[2023-05-02 13:13:35] [DEBUG] Starting new HTTP connection (1): www.openbioinformatics.org:80
#[2023-05-02 13:13:36] [DEBUG] http://www.openbioinformatics.org:80 "GET /annovar/download/hg38_refGeneMrna.fa.gz HTTP/1.1" 200 69639707
#[2023-05-02 13:14:24] [DEBUG] Extract file hg38_refGeneMrna.fa.gz to ./test-db...
#[2023-05-02 13:14:28] [INFO] End


On hg38_avdblist.txt I have all available db such as gnomad clinvar and so on,

Best,

JB

**Comment by antonylebechec** [comment]
done.
