### ISSUE TITLE
Issue while using relative input path

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#84]
Hi,

It should be great to add "os.path.abspath" in output folder creation to avoid this issue:
 line 127, in from_annovar
    raise ValueError(f"Fail create output folder '{output_dirname}'")
ValueError: Fail create output folder ''

In that way we could pass relative path in input
CMD:
howard from_annovar --input=hg38_dbnsfp42a.txt --to_parquet=hg38_dbnsfp42a.parquet --annovar-code=dbnsfp42a --threads=16 --genome=<genomepathfasta> --output=hg38_dbnsfp42a.vcf.gz &

Best,

JB

**Comment by antonylebechec** [comment]
done.
