### ISSUE TITLE
Error loading VCF

### ISSUE THREAD

**Issue by JbaptisteLam** [bioinfo-chru-strasbourg/howard#86]
Hi,

duckdb.InvalidInputException: Invalid Input Error: Error in file XXXXXX on line 2779: expected 1 values per row, but got more
This issue comes from this variants below but it gave the same behaviour with all my variants in my vcf,
It probabably comes from the combination of delim "\t" and autodetect,in duckdb query "FROM read_csv"  it will need a bunch of different input to figure out what's going on

chr1    602281  .       C       CT      1147    PASS    CIGAR=1M1I;RU=T;REFREP=1;IDREP=2;MQ=20;BCSQ=non_coding|ENSG00000230021||processed_transcript;gnomad_popmax_af=0.000100402;gnomad_popmax_af_filter;gnomad_nhomalt=0;gnomad_nhomalt_filter;topmed_af=0.014518;highest_impact_order=50;DeNovoCNN_probability=0.597;ANNOVAR_DATE=2020-06-08;SIFT_score=.;SIFT_converted_rankscore=.;SIFT_pred=.;SIFT4G_score=.;SIFT4G_converted_rankscore=.;SIFT4G_pred=.;Polyphen2_HDIV_score=.;Polyphen2_HDIV_rankscore=.;Polyphen2_HDIV_pred=.;Polyphen2_HVAR_score=.;Polyphen2_HVAR_rankscore=.;Polyphen2_HVAR_pred=.;LRT_score=.;LRT_converted_rankscore=.;LRT_pred=.;MutationTaster_score=.;MutationTaster_converted_rankscore=.;MutationTaster_pred=.;MutationAssessor_score=.;MutationAssessor_rankscore=.;MutationAssessor_pred=.;FATHMM_score=.;FATHMM_converted_rankscore=.;FATHMM_pred=.;PROVEAN_score=.;PROVEAN_converted_rankscore=.;PROVEAN_pred=.;VEST4_score=.;VEST4_rankscore=.;MetaSVM_score=.;MetaSVM_rankscore=.;MetaSVM_pred=.;MetaLR_score=.;MetaLR_rankscore=.;MetaLR_pred=.;MetaRNN_score=.;MetaRNN_rankscore=.;MetaRNN_pred=.;M-CAP_score=.;M-CAP_rankscore=.;M-CAP_pred=.;REVEL_score=.;REVEL_rankscore=.;MutPred_score=.;MutPred_rankscore=.;MVP_score=.;MVP_rankscore=.;MPC_score=.;MPC_rankscore=.;PrimateAI_score=.;PrimateAI_rankscore=.;PrimateAI_pred=.;DEOGEN2_score=.;DEOGEN2_rankscore=.;DEOGEN2_pred=.;BayesDel_addAF_score=.;BayesDel_addAF_rankscore=.;BayesDel_addAF_pred=.;BayesDel_noAF_score=.;BayesDel_noAF_rankscore=.;BayesDel_noAF_pred=.;ClinPred_score=.;ClinPred_rankscore=.;ClinPred_pred=.;LIST-S2_score=.;LIST-S2_rankscore=.;LIST-S2_pred=.;Aloft_pred=.;Aloft_Confidence=.;CADD_raw=.;CADD_raw_rankscore=.;CADD_phred=.;DANN_score=.;DANN_rankscore=.;fathmm-MKL_coding_score=.;fathmm-MKL_coding_rankscore=.;fathmm-MKL_coding_pred=.;fathmm-XF_coding_score=.;fathmm-XF_coding_rankscore=.;fathmm-XF_coding_pred=.;Eigen-raw_coding=.;Eigen-raw_coding_rankscore=.;Eigen-PC-raw_coding=.;Eigen-PC-raw_coding_rankscore=.;GenoCanyon_score=.;GenoCanyon_rankscore=.;integrated_fitCons_score=.;integrated_fitCons_rankscore=.;integrated_confidence_value=.;LINSIGHT=.;LINSIGHT_rankscore=.;GERP++_NR=.;GERP++_RS=.;GERP++_RS_rankscore=.;phyloP100way_vertebrate=.;phyloP100way_vertebrate_rankscore=.;phyloP30way_mammalian=.;phyloP30way_mammalian_rankscore=.;phastCons100way_vertebrate=.;phastCons100way_vertebrate_rankscore=.;phastCons30way_mammalian=.;phastCons30way_mammalian_rankscore=.;SiPhy_29way_logOdds=.;SiPhy_29way_logOdds_rankscore=.;Interpro_domain=.;GTEx_V8_gene=.;GTEx_V8_tissue=.;ALLELE_ENDGT:GQ:GQX:DPI:AD:ADF:ADR:FT:PL  0/1:604:7:449:57,81:27,39:30,42:PASS:999,0,601  0/0:61:61:26:21,0:5,0:16,0:HighDepth:0,64,633   0/0:13:13:13:12,1:2,0:10,1:LowGQX;HighDepth:0,16,335

Best,

**Comment by antonylebechec** [comment]
New devel branch update may fix this issue. Can you try again?

**Comment by JbaptisteLam** [comment]
Still getting the same issue after updating howard, probably comming from space in INFO field,
Not a proper way to test it, but I don't get any warning or error when I open it with bcftools v1.9,

Best,

**Comment by antonylebechec** [comment]
Try to test with new push on devel!

**Comment by antonylebechec** [comment]
done.
